version: "3.8"

services:
    influxdb:
     image: influxdb:2.7
     container_name: influxdb
     ports:
       - "8086:8086"
     volumes:
      - influxdb-data:/var/lib/influxdb2
     environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=nad
      - DOCKER_INFLUXDB_INIT_PASSWORD=nadine2004
      - DOCKER_INFLUXDB_INIT_ORG=iot_org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_bucket
      - DOCKER_INFLUX_INIT_ADMIN_TOKEN=mytoken1234
    mqtt:
     image: eclipse-mosquitto:2
     container_name: mqtt-broker
     ports:
      - "8883:8883"
     volumes:
      - ../platform/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ../pki:/mosquitto/certs:ro
     restart: unless-stopped
    
    backend:
     build:
      context: ..
      dockerfile: docker/Dockerfile.backend
     container_name: platform-backend
     ports:
      - "5000:5000"
     restart: unless-stopped

    iot-agent:
     build:
      context: ..
      dockerfile: docker/Dockerfile.iot
     container_name: iot-agent
     depends_on:
      - mqtt
      - backend
     restart: unless-stopped

volumes:
    influxdb-data:
