# Règles générales pour tous les devices authentifiés
pattern write iot/%u/data
pattern read  iot/%u/cmd
pattern write iot/%u/log
pattern write iot/%u/status

# Backend de supervision
user backend-server
topic read  iot/+/data
topic read  iot/+/log
topic read  iot/+/status
topic write iot/+/cmd
topic read  $SYS/#
